MH-24: Direct Request Part 2
gkiga/mem-help pull request #33
Opened 2020-10-13 22:11 UTC by sachita1A

Closes #21 

Task Outcome:
Task completed as expected. Chris was able to fix the issue of re-entering the teacher's email in with his branch MH-9. We also made the "Edit Request" form match the "New Request" form.

2020-10-13 22:34 UTC, skhalid1120 requested changes
Need to fix issue under Bobby request page, should be under "index page"

2020-10-14 00:46 UTC, csunidev requested changes
Just a few things. My idea was to have the student be able to update all request information except the accept/decline request and the completed/not completed request fields. This way, it leaves the teacher the option to turn down a request or let the student know when the request is completed. If possible, could you remove the options to select these two states (the radios for accept decline request and mark as completed) from the edit view for the student (lines 38-62 in edit view request model)? You can put your code from those lines in place of lines 84-97 in edit view request if you would like. The way you all did the radio buttons for that is better than the way I currently have it. 

Also, the changes that have been made to index are a little overwhelming. Currently, if we are doubling up on the fields in the index page unless I'm doing something wrong in review. We can definitely bring this up and discuss this as a team but I'm not sure if this simplifies things for the user or makes it harder. 
![Screen Shot 2020-10-13 at 7 43 53 PM](https://user-images.githubusercontent.com/60211415/95930691-bd73d680-0d8c-11eb-8e90-fbdde020657d.png)

2020-10-14 01:41 UTC, skhalid1120 approved these changes
Working fine now.  Looks good

2020-10-14 04:50 UTC, csunidev approved these changes

2020-10-14 04:56 UTC, merged